version: '3.1'
services:
    mysql:
        container_name: nxplay_mysql_front
        image: 'mysql:5.7'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/data/mysql:/var/lib/mysql:cached'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=soplay
            - MYSQL_USER=soplayuser
            - MYSQL_PASSWORD=soplaypassword
        ports:
            - '33061:3306'

    webserver:
        container_name: nxplay_webserver_api_front
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '9099:80'

    php-fpm:
        container_name: nxplay_phpfpm_front
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
